import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, mkdirSync, existsSync } from "fs";
import { execFile } from "child_process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit
https://github.com/cybersader/obsidian-slides-ng
*/
`;

const prod = process.argv[2] === "production";

// Vault-as-dev-environment: dev builds output directly into the vault's
// plugin folder. Prod builds output to the repo root (where the release
// workflow picks up main.js / manifest.json / styles.css).
const outdir = prod ? "./" : "./.obsidian/plugins/slides-ng/";

if (!existsSync(outdir)) {
  mkdirSync(outdir, { recursive: true });
}

// Opt-in auto-reload: when AUTORELOAD=1, every successful rebuild triggers
// `Obsidian plugin:reload id=slides-ng` via the official Obsidian CLI. Save a
// file → esbuild rebuilds → plugin reloads inside the running Obsidian → see
// the change in ~1–2 s with no other keystrokes.
//
// Requires Obsidian 1.12+ with a Catalyst license (the Obsidian.com terminal
// redirector is Catalyst-only). Set OBSIDIAN_CLI to the path of Obsidian.com
// if the default doesn't match your install.
const autoReload = !prod && process.env.AUTORELOAD === "1";
const obsidianBin =
  process.env.OBSIDIAN_CLI ??
  "/mnt/c/Users/Cybersader/AppData/Local/Obsidian/Obsidian.com";

const autoReloadPlugin = {
  name: "slides-ng-auto-reload",
  setup(build) {
    let warnedMissingCli = false;
    build.onEnd((result) => {
      if (result.errors.length > 0) return;
      if (!existsSync(obsidianBin)) {
        if (!warnedMissingCli) {
          console.warn(
            `[auto-reload] Obsidian CLI not found at ${obsidianBin}. ` +
              "Set OBSIDIAN_CLI=/path/to/Obsidian.com or skip AUTORELOAD."
          );
          warnedMissingCli = true;
        }
        return;
      }
      execFile(
        obsidianBin,
        ["vault=obsidian-slides-ng", "plugin:reload", "id=slides-ng"],
        { timeout: 10000 },
        (err) => {
          if (err) console.warn(`[auto-reload] plugin:reload failed: ${err.message}`);
          else console.log("[auto-reload] slides-ng reloaded");
        }
      );
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts", "src/styles.css"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outdir,
  plugins: autoReload ? [autoReloadPlugin] : [],
});

// Sync manifest into the dev vault so Obsidian picks up version/name changes
// without manual copy. In prod, the root manifest.json IS the source of
// truth and esbuild's outdir IS the root, so no copy needed.
if (!prod) {
  copyFileSync("manifest.json", outdir + "manifest.json");
}

if (prod) {
  await context.rebuild();
  // Keep BOTH plugin folders in sync with prod artifacts so manual
  // testing in either vault Just Works after `bun run build`:
  //   - ./.obsidian/plugins/slides-ng/ (repo root opened as a vault)
  //   - ./e2e-vault/.obsidian/plugins/slides-ng/ (the E2E sandbox vault
  //     the user may also test in manually)
  // Avoids the stale-build footgun.
  const syncTargets = [
    "./.obsidian/plugins/slides-ng/",
    "./e2e-vault/.obsidian/plugins/slides-ng/",
  ];
  for (const dir of syncTargets) {
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
    for (const f of ["main.js", "manifest.json", "styles.css"]) {
      if (existsSync(f)) {
        copyFileSync(f, dir + f);
      }
    }
    console.log(`[build] synced main.js/manifest.json/styles.css → ${dir}`);
  }
  process.exit(0);
} else {
  await context.watch();
  console.log(`Watching for changes... (output: ${outdir})`);
  if (autoReload) console.log("[auto-reload] enabled — saving a file will reload slides-ng");
}
