import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, mkdirSync, existsSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit
https://github.com/cybersader/obsidian-slides-ng
*/
`;

const prod = process.argv[2] === "production";

// Vault-as-dev-environment: dev builds output directly into the vault's
// plugin folder. Prod builds output to the repo root (where the release
// workflow picks up main.js / manifest.json / styles.css).
const outdir = prod ? "./" : "./.obsidian/plugins/slides-ng/";

if (!existsSync(outdir)) {
  mkdirSync(outdir, { recursive: true });
}

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts", "src/styles.css"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outdir,
});

// Sync manifest into the dev vault so Obsidian picks up version/name changes
// without manual copy. In prod, the root manifest.json IS the source of
// truth and esbuild's outdir IS the root, so no copy needed.
if (!prod) {
  copyFileSync("manifest.json", outdir + "manifest.json");
}

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
  console.log(`Watching for changes... (output: ${outdir})`);
}
